stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - src/cnnClassifier/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/malaria_dataset.tfrecord

  data_preparation:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_preparation.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_preparation.py
      - src/cnnClassifier/components/data_preparation.py
      - artifacts/data_ingestion/malaria_dataset.tfrecord
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/data_preparation/train.tfrecord
      - artifacts/data_preparation/test.tfrecord
      - artifacts/data_preparation/val.tfrecord

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_03_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_prepare_base_model.py
      - src/cnnClassifier/components/prepare_base_model.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/models/base_model.h5

  training:
    cmd: python src/cnnClassifier/pipeline/stage_04_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_training.py
      - src/cnnClassifier/components/training.py
      - artifacts/data_preparation/train.tfrecord
      - artifacts/data_preparation/test.tfrecord
      - artifacts/data_preparation/val.tfrecord
      - artifacts/models/base_model.h5
      #- config/config.yaml
      #- params.yaml
    outs:
      - artifacts/models/malaria_model.h5