stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - src/cnnClassifier/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/malaria_dataset.tfrecord

  data_preparation:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_preparation.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_preparation.py
      - src/cnnClassifier/components/data_preparation.py
      - artifacts/data_ingestion/malaria_dataset.tfrecord
      - config/config.yaml
    outs:
      - artifacts/data_preparation/train.tfrecord
      - artifacts/data_preparation/test.tfrecord
      - artifacts/data_preparation/val.tfrecord