IMAGE_SIZE: 224
BATCH_SIZE: 32
SHUFFLE_BUFFER_SIZE: 8
DATASET_SIZE: 27558

DENSE_LAYER_ONE_SIZE: 100
DENSE_LAYER_TWO_SIZE: 10
STRIDE_LENGTH: 1
KERNEL_SIZE: 3
POOL_SIZE: 2
FILTERS: 16
OUTPUT_CLASSES: 1

EPOCHS: 1
INITIAL_LEARNING_RATE: 0.01
LEARNING_RATE_FACTOR: 0.1
EARLY_STOPPING_PATIENCE: 5
LEARNING_RATE_PATIENCE: 3
