artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/malaria_dataset.tfrecord

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5